/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_v1_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Fundamentals Sync */
        post: operations["trigger_fundamentals_sync_api_v1_admin_ingestion_fundamentals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/sec-directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sec Directory Sync */
        post: operations["trigger_sec_directory_sync_api_v1_admin_ingestion_sec_directory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/provider-fetches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Fetches */
        get: operations["provider_fetches_api_v1_admin_provider_fetches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Config */
        get: operations["auth_config_api_v1_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oidc Login */
        get: operations["oidc_login_api_v1_auth_oidc_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Profile */
        get: operations["company_profile_api_v1_companies__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Filings */
        get: operations["list_filings_api_v1_companies__ticker__filings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load History */
        post: operations["load_history_api_v1_companies__ticker__filings_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Documents
         * @description Load, split, and embed the newest documents of the given forms for search.
         */
        post: operations["index_documents_api_v1_companies__ticker__filings_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings/{accession}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filing Detail */
        get: operations["filing_detail_api_v1_companies__ticker__filings__accession__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings/{accession}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Section Diff */
        get: operations["section_diff_api_v1_companies__ticker__filings__accession__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fundamentals */
        get: operations["fundamentals_api_v1_companies__ticker__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/insiders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insiders */
        get: operations["insiders_api_v1_companies__ticker__insiders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Metrics */
        get: operations["latest_metrics_api_v1_companies__ticker__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Peers */
        get: operations["peers_api_v1_companies__ticker__peers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/{ticker}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Bars */
        get: operations["daily_bars_api_v1_market_data__ticker__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screen */
        post: operations["screen_api_v1_screener_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metric Catalog */
        get: operations["metric_catalog_api_v1_screener_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sectors */
        get: operations["sectors_api_v1_screener_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/filings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Filings */
        get: operations["search_filings_api_v1_search_filings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_v1_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_v1_watchlists__watchlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_v1_watchlists__watchlist_id__items__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserOut */
        AdminUserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Role */
            role?: ("viewer" | "analyst" | "admin") | null;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /** AuthConfigOut */
        AuthConfigOut: {
            /** Auth Disabled */
            auth_disabled: boolean;
            /** Oidc */
            oidc: boolean;
            /** Password Login */
            password_login: boolean;
            /** Registration */
            registration: boolean;
        };
        /** CellOut */
        CellOut: {
            /** Accession */
            accession: string | null;
            /** Concept */
            concept: string | null;
            /** Derivation */
            derivation: string | null;
            /**
             * Filed Date
             * Format: date
             */
            filed_date: string;
            /** Period Key */
            period_key: string;
            /** Value */
            value: number;
        };
        /** Classification */
        Classification: {
            /** Code */
            code: string;
            /** Industry */
            industry: string | null;
            /** Sector */
            sector: string | null;
            /**
             * System
             * @constant
             */
            system: "SIC";
        };
        /** CompanyMetricsResponse */
        CompanyMetricsResponse: {
            /** Computed At */
            computed_at: string | null;
            /** Formula Version */
            formula_version: string | null;
            /** Metrics */
            metrics: components["schemas"]["SnapshotMetricOut"][];
            /** Ticker */
            ticker: string;
        };
        /** CompanyProfile */
        CompanyProfile: {
            /** Availability */
            availability: {
                [key: string]: components["schemas"]["DataAvailability"];
            };
            /** Cik */
            cik: number | null;
            classification: components["schemas"]["Classification"] | null;
            /** Country */
            country: string | null;
            /** Description */
            description: string | null;
            /** Entity Type */
            entity_type: string | null;
            /** Exchange */
            exchange: string | null;
            /** Filer Category */
            filer_category: string | null;
            /** Fiscal Year End */
            fiscal_year_end: string | null;
            /** Former Names */
            former_names: components["schemas"]["FormerName"][];
            /** Headquarters */
            headquarters: string | null;
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** Name */
            name: string;
            /** Profile Message */
            profile_message: string | null;
            /**
             * Profile Status
             * @enum {string}
             */
            profile_status: "current" | "stale" | "unavailable" | "not_configured" | "not_applicable";
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** State Of Incorporation */
            state_of_incorporation: string | null;
            /** Ticker */
            ticker: string;
            /** Website */
            website: string | null;
        };
        /** CompanySearchResponse */
        CompanySearchResponse: {
            /** Items */
            items: components["schemas"]["CompanySummary"][];
            /** Total */
            total: number;
        };
        /** CompanySummary */
        CompanySummary: {
            /** Cik */
            cik: number | null;
            /** Country */
            country: string | null;
            /** Exchange */
            exchange: string | null;
            /** Industry */
            industry: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Ticker */
            ticker: string;
        };
        /** DailyBarOut */
        DailyBarOut: {
            /** Adj Close */
            adj_close: number | null;
            /** Adj High */
            adj_high: number | null;
            /** Adj Low */
            adj_low: number | null;
            /** Adj Open */
            adj_open: number | null;
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Dividend Cash */
            dividend_cash: number | null;
            /** Fetch Id */
            fetch_id: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Split Factor */
            split_factor: number | null;
            /** Volume */
            volume: number;
        };
        /** DataAvailability */
        DataAvailability: {
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "not_configured" | "planned";
        };
        /** DataQuality */
        DataQuality: {
            /** Rejected Count */
            rejected_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "cached" | "stale";
            /** Warnings */
            warnings: string[];
        };
        /** DiffBlockOut */
        DiffBlockOut: {
            /** After */
            after: string | null;
            /** Before */
            before: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "same" | "added" | "removed" | "changed";
            /** Words */
            words: components["schemas"]["WordOpOut"][];
        };
        /** DiffSummaryOut */
        DiffSummaryOut: {
            /** Added */
            added: number;
            /** Changed */
            changed: number;
            /** Removed */
            removed: number;
            /** Same */
            same: number;
            /** Words Added */
            words_added: number;
            /** Words Removed */
            words_removed: number;
        };
        /** DirectoryStats */
        DirectoryStats: {
            /** Active Securities */
            active_securities: number;
            /** Companies */
            companies: number;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** FilingDetail */
        FilingDetail: {
            /** Extractor Version */
            extractor_version: string | null;
            filing: components["schemas"]["FilingOut"];
            previous: components["schemas"]["FilingOut"] | null;
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Ticker */
            ticker: string;
        };
        /** FilingOut */
        FilingOut: {
            /** Accepted At */
            accepted_at: string | null;
            /** Accession */
            accession: string;
            /** Description */
            description: string | null;
            /** Document Error */
            document_error: string | null;
            /**
             * Document Status
             * @enum {string}
             */
            document_status: "not_loaded" | "loaded" | "failed" | "unsupported" | "not_issuer";
            /** Document Url */
            document_url: string | null;
            /**
             * Filed Date
             * Format: date
             */
            filed_date: string;
            /** Form */
            form: string;
            /** Items */
            items: string[];
            /** Report Date */
            report_date: string | null;
            /** Sec Url */
            sec_url: string;
            /** Size */
            size: number | null;
        };
        /** FilingsResponse */
        FilingsResponse: {
            /** Cik */
            cik: number | null;
            /** Documents Loaded */
            documents_loaded: number;
            /** Filings */
            filings: components["schemas"]["FilingOut"][];
            /** Forms */
            forms: components["schemas"]["FormCount"][];
            /** History Loaded */
            history_loaded: boolean;
            /** Message */
            message: string | null;
            /** Passages */
            passages: number;
            /** Passages Embeddable */
            passages_embeddable: number;
            /** Passages Embedded */
            passages_embedded: number;
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /**
             * Status
             * @enum {string}
             */
            status: "current" | "stale" | "unavailable" | "not_configured" | "not_applicable";
            /** Ticker */
            ticker: string;
            /** Total */
            total: number;
        };
        /** Filter */
        Filter: {
            /** Max */
            max?: number | null;
            /** Metric */
            metric: string;
            /** Min */
            min?: number | null;
        };
        /** FormCount */
        FormCount: {
            /** Count */
            count: number;
            /** Form */
            form: string;
        };
        /** FormerName */
        FormerName: {
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Name */
            name: string;
        };
        /** FundamentalsResponse */
        FundamentalsResponse: {
            /** As Of */
            as_of: string | null;
            /** Cik */
            cik: number | null;
            /** Formula Version */
            formula_version: string;
            /** Mapping Version */
            mapping_version: string;
            /** Message */
            message: string | null;
            /** Metrics */
            metrics: components["schemas"]["MetricSeriesOut"][];
            /**
             * Period Type
             * @enum {string}
             */
            period_type: "annual" | "quarterly";
            /** Periods */
            periods: components["schemas"]["PeriodOut"][];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            statements: components["schemas"]["StatementsOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "current" | "stale" | "unavailable" | "not_configured" | "not_applicable" | "not_available";
            /** Ticker */
            ticker: string;
        };
        /** FundamentalsSyncIn */
        FundamentalsSyncIn: {
            /** Tickers */
            tickers: string[];
        };
        /** FundamentalsSyncResult */
        FundamentalsSyncResult: {
            /** Message */
            message: string | null;
            /** Status */
            status: string;
            /** Ticker */
            ticker: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryOut */
        HistoryOut: {
            /** Added */
            added: number;
            /** Ticker */
            ticker: string;
        };
        /** IndexDocumentsIn */
        IndexDocumentsIn: {
            /**
             * Embed Limit
             * @default 200
             */
            embed_limit: number;
            /** Forms */
            forms?: string[];
            /**
             * Limit
             * @default 8
             */
            limit: number;
        };
        /** IndexDocumentsOut */
        IndexDocumentsOut: {
            /** Embedded */
            embedded: number;
            /** Embedding Model */
            embedding_model: string | null;
            /** Embedding Remaining */
            embedding_remaining: number;
            /** Outcome */
            outcome: {
                [key: string]: number;
            };
            /** Ticker */
            ticker: string;
        };
        /** InsiderSummary */
        InsiderSummary: {
            /** Months */
            months: number;
            purchases: components["schemas"]["TradeTotals"];
            sales: components["schemas"]["TradeTotals"];
            /**
             * Since
             * Format: date
             */
            since: string;
        };
        /** InsiderTransactionOut */
        InsiderTransactionOut: {
            /** Accession */
            accession: string;
            /** Acquired Disposed */
            acquired_disposed: string | null;
            /** Exercise Price */
            exercise_price: number | null;
            /**
             * Filed Date
             * Format: date
             */
            filed_date: string;
            /** Form */
            form: string;
            /** Is Derivative */
            is_derivative: boolean;
            /** Is Director */
            is_director: boolean;
            /** Is Officer */
            is_officer: boolean;
            /** Is Ten Percent Owner */
            is_ten_percent_owner: boolean;
            /** Joint Owners */
            joint_owners: number;
            /** Officer Title */
            officer_title: string | null;
            /** Owner Cik */
            owner_cik: number | null;
            /** Owner Name */
            owner_name: string;
            /** Ownership */
            ownership: string | null;
            /** Ownership Nature */
            ownership_nature: string | null;
            /** Price */
            price: number | null;
            /** Rule 10B5 1 */
            rule_10b5_1: boolean | null;
            /** Sec Url */
            sec_url: string;
            /** Security Title */
            security_title: string | null;
            /** Shares */
            shares: number | null;
            /** Shares Owned After */
            shares_owned_after: number | null;
            /** Transaction Code */
            transaction_code: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Underlying Security */
            underlying_security: string | null;
            /** Value */
            value: number | null;
        };
        /** InsidersResponse */
        InsidersResponse: {
            /** Filings Loaded */
            filings_loaded: number;
            /** Filings Pending */
            filings_pending: number;
            /** Message */
            message: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "current" | "stale" | "unavailable" | "not_configured" | "not_applicable";
            summary: components["schemas"]["InsiderSummary"];
            /** Ticker */
            ticker: string;
            /** Transactions */
            transactions: components["schemas"]["InsiderTransactionOut"][];
        };
        /** LineItemOut */
        LineItemOut: {
            /** Cells */
            cells: components["schemas"]["CellOut"][];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "USD" | "USD/shares" | "shares";
        };
        /** ListingOut */
        ListingOut: {
            /** Exchange */
            exchange: string | null;
            /** First Seen At */
            first_seen_at: string | null;
            /** Is Active */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Ticker */
            ticker: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarketBarsResponse */
        MarketBarsResponse: {
            /** Bars */
            bars: components["schemas"]["DailyBarOut"][];
            /**
             * Interval
             * @constant
             */
            interval: "1d";
            /** Provider */
            provider: string;
            quality: components["schemas"]["DataQuality"];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            summary: components["schemas"]["PriceSummary"] | null;
            /** Ticker */
            ticker: string;
        };
        /** MetricPointOut */
        MetricPointOut: {
            /** Period Key */
            period_key: string;
            /** Value */
            value: number;
        };
        /** MetricSeriesOut */
        MetricSeriesOut: {
            /** Category */
            category: string;
            /** Formula */
            formula: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "percent" | "ratio" | "currency" | "shares" | "per_share";
            /** Values */
            values: components["schemas"]["MetricPointOut"][];
        };
        /** PeerRow */
        PeerRow: {
            /** Industry */
            industry: string | null;
            /** Is Subject */
            is_subject: boolean;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Name */
            name: string;
            /** Sic Code */
            sic_code: string | null;
            /** Ticker */
            ticker: string;
        };
        /** PeersResponse */
        PeersResponse: {
            /** Basis */
            basis: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: components["schemas"]["PeerRow"][];
            /** Ticker */
            ticker: string;
        };
        /** PeriodOut */
        PeriodOut: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** Fiscal Quarter */
            fiscal_quarter: number | null;
            /** Fiscal Year */
            fiscal_year: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** PriceSummary */
        PriceSummary: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "adjusted" | "raw";
            /** Change */
            change: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Last Close */
            last_close: number;
            /** Previous Close */
            previous_close: number | null;
        };
        /** ProviderFetchOut */
        ProviderFetchOut: {
            /** Dataset */
            dataset: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Http Status */
            http_status: number | null;
            /** Id */
            id: number;
            /** Latency Ms */
            latency_ms: number;
            /** Provider */
            provider: string;
            /** Record Count */
            record_count: number | null;
            /** Rejected Count */
            rejected_count: number | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Status */
            status: string;
            /** Subject */
            subject: string | null;
        };
        /** ProviderHealth */
        ProviderHealth: {
            /** Configured */
            configured: boolean;
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "reference" | "market_data";
            /** Last Error At */
            last_error_at: string | null;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Message */
            message: string;
            /** Name */
            name: string | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ScreenMetricOut */
        ScreenMetricOut: {
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Price Based */
            price_based: boolean;
            /**
             * Unit
             * @enum {string}
             */
            unit: "percent" | "ratio" | "currency" | "multiple";
        };
        /** ScreenRequest */
        ScreenRequest: {
            /** Columns */
            columns?: string[];
            /** Filters */
            filters?: components["schemas"]["Filter"][];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Sector */
            sector?: string | null;
            /**
             * Sort By
             * @default market_cap
             */
            sort_by: string;
            /**
             * Sort Dir
             * @default desc
             * @enum {string}
             */
            sort_dir: "asc" | "desc";
        };
        /** ScreenResponse */
        ScreenResponse: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: components["schemas"]["ScreenRow"][];
            /** Total */
            total: number;
            /** Universe */
            universe: number;
        };
        /** ScreenRow */
        ScreenRow: {
            /** Exchange */
            exchange: string | null;
            /** Industry */
            industry: string | null;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Metrics As Of */
            metrics_as_of: {
                [key: string]: string | null;
            };
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Ticker */
            ticker: string;
        };
        /** SearchHitOut */
        SearchHitOut: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Company Name */
            company_name: string;
            filing: components["schemas"]["FilingOut"];
            /** Score */
            score: number;
            /** Section Key */
            section_key: string;
            /** Section Title */
            section_title: string;
            /** Snippet */
            snippet: string;
            /** Text Rank */
            text_rank: number | null;
            /** Ticker */
            ticker: string | null;
            /** Vector Distance */
            vector_distance: number | null;
            /** Vector Rank */
            vector_rank: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Embedding Model */
            embedding_model: string | null;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "text";
            /** Query */
            query: string;
        };
        /** SectionDiffOut */
        SectionDiffOut: {
            /** Blocks */
            blocks: components["schemas"]["DiffBlockOut"][];
            /** Comparable */
            comparable: boolean;
            current: components["schemas"]["FilingOut"];
            previous: components["schemas"]["FilingOut"];
            /** Section Key */
            section_key: string;
            summary: components["schemas"]["DiffSummaryOut"] | null;
            /** Ticker */
            ticker: string;
            /** Title */
            title: string;
        };
        /** SectionOut */
        SectionOut: {
            /** Char Count */
            char_count: number;
            /** Item */
            item: string | null;
            /** Key */
            key: string;
            /** Part */
            part: string | null;
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Auth Method */
            auth_method: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /** SnapshotMetricOut */
        SnapshotMetricOut: {
            /** Available Date */
            available_date: string | null;
            /** Basis */
            basis: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Period End */
            period_end: string | null;
            /** Price Based */
            price_based: boolean;
            /**
             * Unit
             * @enum {string}
             */
            unit: "percent" | "ratio" | "currency" | "multiple";
            /** Value */
            value: number;
        };
        /**
         * SourceRef
         * @description Where a set of values came from. Every externally sourced field links to one.
         */
        SourceRef: {
            /** Dataset */
            dataset: string;
            /** Fetch Id */
            fetch_id: number;
            /** License Note */
            license_note: string | null;
            /** Provider */
            provider: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Url */
            source_url: string;
        };
        /** StatementsOut */
        StatementsOut: {
            /** Balance */
            balance: components["schemas"]["LineItemOut"][];
            /** Cash Flow */
            cash_flow: components["schemas"]["LineItemOut"][];
            /** Income */
            income: components["schemas"]["LineItemOut"][];
        };
        /** SystemStatus */
        SystemStatus: {
            directory: components["schemas"]["DirectoryStats"];
            /** Environment */
            environment: string;
            /** Providers */
            providers: components["schemas"]["ProviderHealth"][];
        };
        /** TradeTotals */
        TradeTotals: {
            /** Insiders */
            insiders: number;
            /** Shares */
            shares: number;
            /** Transactions */
            transactions: number;
            /** Value */
            value: number;
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Name */
            name: string;
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /** Ticker */
            ticker: string;
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Exchange */
            exchange: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["WatchlistItemOut"][];
            /** Name */
            name: string;
        };
        /** WordOpOut */
        WordOpOut: {
            /**
             * Op
             * @enum {string}
             */
            op: "equal" | "insert" | "delete";
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_events_api_v1_admin_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_fundamentals_sync_api_v1_admin_ingestion_fundamentals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundamentalsSyncIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalsSyncResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sec_directory_sync_api_v1_admin_ingestion_sec_directory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | boolean;
                    };
                };
            };
        };
    };
    provider_fetches_api_v1_admin_provider_fetches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderFetchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_v1_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigOut"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidc_login_api_v1_auth_oidc_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    search_api_v1_companies_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_profile_api_v1_companies__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_filings_api_v1_companies__ticker__filings_get: {
        parameters: {
            query?: {
                /** @description Comma-separated, e.g. 10-K,10-Q */
                forms?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_history_api_v1_companies__ticker__filings_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_documents_api_v1_companies__ticker__filings_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexDocumentsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexDocumentsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filing_detail_api_v1_companies__ticker__filings__accession__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
                accession: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    section_diff_api_v1_companies__ticker__filings__accession__diff_get: {
        parameters: {
            query: {
                /** @description Section key, e.g. item_1a */
                section: string;
            };
            header?: never;
            path: {
                ticker: string;
                accession: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fundamentals_api_v1_companies__ticker__fundamentals_get: {
        parameters: {
            query?: {
                period?: "annual" | "quarterly";
                /** @description Only data public on or before */
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insiders_api_v1_companies__ticker__insiders_get: {
        parameters: {
            query?: {
                months?: number;
                /** @description Form 4s to fetch now */
                load?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsidersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_metrics_api_v1_companies__ticker__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peers_api_v1_companies__ticker__peers_get: {
        parameters: {
            query?: {
                /** @description Comma-separated extra peers */
                tickers?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_bars_api_v1_market_data__ticker__bars_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                interval?: "1d";
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketBarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screener_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_catalog_api_v1_screener_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenMetricOut"][];
                };
            };
        };
    };
    sectors_api_v1_screener_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    search_filings_api_v1_search_filings_get: {
        parameters: {
            query: {
                q: string;
                /** @description Comma-separated tickers */
                tickers?: string | null;
                /** @description Comma-separated forms */
                forms?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"][];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_v1_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_v1_watchlists__watchlist_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_v1_watchlists__watchlist_id__items__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
