/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_v1_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/sec-directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sec Directory Sync */
        post: operations["trigger_sec_directory_sync_api_v1_admin_ingestion_sec_directory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/provider-fetches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Fetches */
        get: operations["provider_fetches_api_v1_admin_provider_fetches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Config */
        get: operations["auth_config_api_v1_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oidc Login */
        get: operations["oidc_login_api_v1_auth_oidc_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Profile */
        get: operations["company_profile_api_v1_companies__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/{ticker}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Bars */
        get: operations["daily_bars_api_v1_market_data__ticker__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_v1_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_v1_watchlists__watchlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_v1_watchlists__watchlist_id__items__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserOut */
        AdminUserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Role */
            role?: ("viewer" | "analyst" | "admin") | null;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /** AuthConfigOut */
        AuthConfigOut: {
            /** Oidc */
            oidc: boolean;
            /** Password Login */
            password_login: boolean;
            /** Registration */
            registration: boolean;
        };
        /** Classification */
        Classification: {
            /** Code */
            code: string;
            /** Industry */
            industry: string | null;
            /** Sector */
            sector: string | null;
            /**
             * System
             * @constant
             */
            system: "SIC";
        };
        /** CompanyProfile */
        CompanyProfile: {
            /** Availability */
            availability: {
                [key: string]: components["schemas"]["DataAvailability"];
            };
            /** Cik */
            cik: number | null;
            classification: components["schemas"]["Classification"] | null;
            /** Country */
            country: string | null;
            /** Description */
            description: string | null;
            /** Entity Type */
            entity_type: string | null;
            /** Exchange */
            exchange: string | null;
            /** Filer Category */
            filer_category: string | null;
            /** Fiscal Year End */
            fiscal_year_end: string | null;
            /** Former Names */
            former_names: components["schemas"]["FormerName"][];
            /** Headquarters */
            headquarters: string | null;
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** Name */
            name: string;
            /** Profile Message */
            profile_message: string | null;
            /**
             * Profile Status
             * @enum {string}
             */
            profile_status: "current" | "stale" | "unavailable" | "not_configured" | "not_applicable";
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** State Of Incorporation */
            state_of_incorporation: string | null;
            /** Ticker */
            ticker: string;
            /** Website */
            website: string | null;
        };
        /** CompanySearchResponse */
        CompanySearchResponse: {
            /** Items */
            items: components["schemas"]["CompanySummary"][];
            /** Total */
            total: number;
        };
        /** CompanySummary */
        CompanySummary: {
            /** Cik */
            cik: number | null;
            /** Country */
            country: string | null;
            /** Exchange */
            exchange: string | null;
            /** Industry */
            industry: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Ticker */
            ticker: string;
        };
        /** DailyBarOut */
        DailyBarOut: {
            /** Adj Close */
            adj_close: number | null;
            /** Adj High */
            adj_high: number | null;
            /** Adj Low */
            adj_low: number | null;
            /** Adj Open */
            adj_open: number | null;
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Dividend Cash */
            dividend_cash: number | null;
            /** Fetch Id */
            fetch_id: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Split Factor */
            split_factor: number | null;
            /** Volume */
            volume: number;
        };
        /** DataAvailability */
        DataAvailability: {
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "not_configured" | "planned";
        };
        /** DataQuality */
        DataQuality: {
            /** Rejected Count */
            rejected_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "cached" | "stale";
            /** Warnings */
            warnings: string[];
        };
        /** DirectoryStats */
        DirectoryStats: {
            /** Active Securities */
            active_securities: number;
            /** Companies */
            companies: number;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** FormerName */
        FormerName: {
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListingOut */
        ListingOut: {
            /** Exchange */
            exchange: string | null;
            /** First Seen At */
            first_seen_at: string | null;
            /** Is Active */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Ticker */
            ticker: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarketBarsResponse */
        MarketBarsResponse: {
            /** Bars */
            bars: components["schemas"]["DailyBarOut"][];
            /**
             * Interval
             * @constant
             */
            interval: "1d";
            /** Provider */
            provider: string;
            quality: components["schemas"]["DataQuality"];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            summary: components["schemas"]["PriceSummary"] | null;
            /** Ticker */
            ticker: string;
        };
        /** PriceSummary */
        PriceSummary: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "adjusted" | "raw";
            /** Change */
            change: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Last Close */
            last_close: number;
            /** Previous Close */
            previous_close: number | null;
        };
        /** ProviderFetchOut */
        ProviderFetchOut: {
            /** Dataset */
            dataset: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Http Status */
            http_status: number | null;
            /** Id */
            id: number;
            /** Latency Ms */
            latency_ms: number;
            /** Provider */
            provider: string;
            /** Record Count */
            record_count: number | null;
            /** Rejected Count */
            rejected_count: number | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Status */
            status: string;
            /** Subject */
            subject: string | null;
        };
        /** ProviderHealth */
        ProviderHealth: {
            /** Configured */
            configured: boolean;
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "reference" | "market_data";
            /** Last Error At */
            last_error_at: string | null;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Message */
            message: string;
            /** Name */
            name: string | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Auth Method */
            auth_method: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * SourceRef
         * @description Where a set of values came from. Every externally sourced field links to one.
         */
        SourceRef: {
            /** Dataset */
            dataset: string;
            /** Fetch Id */
            fetch_id: number;
            /** License Note */
            license_note: string | null;
            /** Provider */
            provider: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Url */
            source_url: string;
        };
        /** SystemStatus */
        SystemStatus: {
            directory: components["schemas"]["DirectoryStats"];
            /** Environment */
            environment: string;
            /** Providers */
            providers: components["schemas"]["ProviderHealth"][];
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Name */
            name: string;
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /** Ticker */
            ticker: string;
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Exchange */
            exchange: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["WatchlistItemOut"][];
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_events_api_v1_admin_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sec_directory_sync_api_v1_admin_ingestion_sec_directory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | boolean;
                    };
                };
            };
        };
    };
    provider_fetches_api_v1_admin_provider_fetches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderFetchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_v1_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigOut"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidc_login_api_v1_auth_oidc_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    search_api_v1_companies_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_profile_api_v1_companies__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_bars_api_v1_market_data__ticker__bars_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                interval?: "1d";
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketBarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"][];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_v1_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_v1_watchlists__watchlist_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_v1_watchlists__watchlist_id__items__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
