"""Phase 6: macro data, PIT universe, features, models, predictions, 13F, Bitcoin prices."""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0007_quant"
down_revision: str | None = "0006_valuation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_regimes",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("version", "as_of", name=op.f("pk_market_regimes")),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("target", sa.String(length=60), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("feature_set_version", sa.String(length=20), nullable=False),
        sa.Column("universe_version", sa.String(length=20), nullable=False),
        sa.Column("code_version", sa.String(length=20), nullable=False),
        sa.Column("trained_from", sa.Date(), nullable=False),
        sa.Column("trained_through", sa.Date(), nullable=False),
        sa.Column("feature_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("importance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
    )
    op.create_index(
        "ix_model_versions_name_created", "model_versions", ["name", "created_at"], unique=False
    )
    op.create_table(
        "crypto_prices",
        sa.Column("pair", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("volume_usd", sa.Numeric(precision=28, scale=2), nullable=True),
        sa.Column("trades", sa.BigInteger(), nullable=True),
        sa.Column("fetch_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_crypto_prices_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("pair", "trade_date", name=op.f("pk_crypto_prices")),
    )
    op.create_index(op.f("ix_crypto_prices_fetch_id"), "crypto_prices", ["fetch_id"], unique=False)
    op.create_table(
        "macro_series",
        sa.Column("series_id", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("units", sa.String(length=120), nullable=False),
        sa.Column("frequency", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("release_lag_days", sa.Integer(), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetch_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_macro_series_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("series_id", name=op.f("pk_macro_series")),
    )
    op.create_table(
        "cusip_mappings",
        sa.Column("cusip", sa.String(length=9), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("composite_figi", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("exch_code", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("security_type", sa.String(length=60), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("fetch_id", sa.BigInteger(), nullable=False),
        sa.Column("mapped_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_cusip_mappings_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_cusip_mappings_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("cusip", name=op.f("pk_cusip_mappings")),
    )
    op.create_index(
        op.f("ix_cusip_mappings_company_id"), "cusip_mappings", ["company_id"], unique=False
    )
    op.create_table(
        "factor_scores",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("factor", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_factor_scores_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "version", "as_of", "company_id", "factor", name=op.f("pk_factor_scores")
        ),
    )
    op.create_index(
        "ix_factor_scores_company", "factor_scores", ["company_id", "as_of"], unique=False
    )
    op.create_table(
        "feature_snapshots",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_available_on", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_feature_snapshots_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "version", "as_of", "company_id", name=op.f("pk_feature_snapshots")
        ),
    )
    op.create_index(
        "ix_feature_snapshots_company", "feature_snapshots", ["company_id", "as_of"], unique=False
    )
    op.create_table(
        "institutional_holdings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=False),
        sa.Column("filer_cik", sa.Integer(), nullable=False),
        sa.Column("filer_name", sa.String(length=200), nullable=False),
        sa.Column("accession", sa.String(length=25), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("shares", sa.Numeric(precision=24, scale=0), nullable=False),
        sa.Column("value_usd", sa.Numeric(precision=24, scale=0), nullable=False),
        sa.Column("fetch_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_institutional_holdings_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_institutional_holdings_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_holdings")),
    )
    op.create_index(
        "ix_institutional_holdings_company_period",
        "institutional_holdings",
        ["company_id", "period_of_report"],
        unique=False,
    )
    op.create_table(
        "macro_observations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("series_id", sa.String(length=40), nullable=False),
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("realtime_start", sa.Date(), nullable=False),
        sa.Column("realtime_end", sa.Date(), nullable=False),
        sa.Column("available_on", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("fetch_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_macro_observations_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["macro_series.series_id"],
            name=op.f("fk_macro_observations_series_id_macro_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_observations")),
        sa.UniqueConstraint(
            "series_id",
            "observation_date",
            "realtime_start",
            name=op.f("uq_macro_observations_series_id_observation_date_realtime_start"),
        ),
    )
    op.create_index(
        op.f("ix_macro_observations_fetch_id"), "macro_observations", ["fetch_id"], unique=False
    )
    op.create_index(
        "ix_macro_observations_series_available",
        "macro_observations",
        ["series_id", "available_on"],
        unique=False,
    )
    op.create_table(
        "ownership_summaries",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=False),
        sa.Column("holders", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Numeric(precision=24, scale=0), nullable=False),
        sa.Column("value_usd", sa.Numeric(precision=24, scale=0), nullable=False),
        sa.Column("cusips", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset", sa.String(length=120), nullable=False),
        sa.Column("fetch_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_ownership_summaries_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["provider_fetches.id"],
            name=op.f("fk_ownership_summaries_fetch_id_provider_fetches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "company_id", "period_of_report", name=op.f("pk_ownership_summaries")
        ),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("probability_raw", sa.Float(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("expected_excess", sa.Float(), nullable=True),
        sa.Column("excess_low", sa.Float(), nullable=True),
        sa.Column("excess_high", sa.Float(), nullable=True),
        sa.Column("drivers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_available_on", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_predictions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "model_version_id",
            "company_id",
            "as_of",
            name=op.f("uq_predictions_model_version_id_company_id_as_of"),
        ),
    )
    op.create_index(
        "ix_predictions_company_as_of", "predictions", ["company_id", "as_of"], unique=False
    )
    op.create_index(
        op.f("ix_predictions_model_version_id"), "predictions", ["model_version_id"], unique=False
    )
    op.create_table(
        "universe_candidates",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("best_rank", sa.Integer(), nullable=False),
        sa.Column("best_year", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_universe_candidates_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", name=op.f("pk_universe_candidates")),
    )
    op.create_table(
        "prediction_outcomes",
        sa.Column("prediction_id", sa.BigInteger(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("excess_return", sa.Float(), nullable=False),
        sa.Column("went_up", sa.Boolean(), nullable=False),
        sa.Column("brier", sa.Float(), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_prediction_outcomes_prediction_id_predictions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_prediction_outcomes")),
    )
    op.create_table(
        "price_coverage",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("loaded_from", sa.Date(), nullable=True),
        sa.Column("loaded_through", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_price_coverage_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", "provider", name=op.f("pk_price_coverage")),
    )
    op.create_table(
        "universe_members",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("revenue_ttm", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("revenue_basis", sa.String(length=40), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=True),
        sa.Column("has_prices", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_universe_members_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_universe_members_security_id_securities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("version", "as_of", "company_id", name=op.f("pk_universe_members")),
    )
    op.create_index(
        "ix_universe_members_company", "universe_members", ["company_id", "as_of"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_universe_members_company", table_name="universe_members")
    op.drop_table("universe_members")
    op.drop_table("price_coverage")
    op.drop_table("prediction_outcomes")
    op.drop_table("universe_candidates")
    op.drop_index(op.f("ix_predictions_model_version_id"), table_name="predictions")
    op.drop_index("ix_predictions_company_as_of", table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("ownership_summaries")
    op.drop_index("ix_macro_observations_series_available", table_name="macro_observations")
    op.drop_index(op.f("ix_macro_observations_fetch_id"), table_name="macro_observations")
    op.drop_table("macro_observations")
    op.drop_index("ix_institutional_holdings_company_period", table_name="institutional_holdings")
    op.drop_table("institutional_holdings")
    op.drop_index("ix_feature_snapshots_company", table_name="feature_snapshots")
    op.drop_table("feature_snapshots")
    op.drop_index("ix_factor_scores_company", table_name="factor_scores")
    op.drop_table("factor_scores")
    op.drop_index(op.f("ix_cusip_mappings_company_id"), table_name="cusip_mappings")
    op.drop_table("cusip_mappings")
    op.drop_table("macro_series")
    op.drop_index(op.f("ix_crypto_prices_fetch_id"), table_name="crypto_prices")
    op.drop_table("crypto_prices")
    op.drop_index("ix_model_versions_name_created", table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_table("market_regimes")
    # ### end Alembic commands ###
